name: Dispatch Tag Event

on:
  push:
    branches:
      - 'main'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    env:
      FEEDSTOCK_SPEC: "${{ github.repository }}"
      REF: "${{ github.ref }}"
      IS_BETA: "${{ contains(github.ref, 'beta') }}"
    steps:
      - name: dispatch tag event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PANGEO_FORGE_BOT_TOKEN }}
          repository: pangeo-forge/registrar
          event-type: dispatch-tag-event
          client-payload: '{"feedstock_spec": "${{ env.FEEDSTOCK_SPEC }}", "ref": "${{ env.REF }}", "is_beta": "${{ env.IS_BETA }}"}'
